site_name: AI Agent Concepts

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: green
      # accent: light green

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: green
      # accent: light green

# extra_css:
#   - stylesheets/extra.css

nav:
  - ğŸ‘‹ Introduction: index.md
  - âœï¸ Basics of Prompt Writing: prompt_writing.md
  - ğŸ“ AI Agent 101: ai_agent_101.md
  - ğŸ› ï¸ Agent Harness: ai_agent_harness.md
  - ğŸ“š Context Engineering: context_engineering.md
  - ğŸ’¾ Memory Management: memory_management.md
  - ğŸ‘¨ğŸ¼â€ğŸ’» Human-In-the-Loop: human_in_the_loop.md
  